### ISSUE TITLE
Suggestion of dopri853 algorithm

### ISSUE THREAD

**Issue by vick2075** [seanie5011/SumResProj2021_COVIDMODELLING#1]
Hi,

Do you use the dopri853 algorithm in this project, created in native Python?

**Comment by seanie5011** [comment]
Hi vick2075,

I have not used the [Dormand-Prince Runge-Kutta of Order 8(5,3)](https://en.wikipedia.org/wiki/Dormand%E2%80%93Prince_method) algorithm in this project. If you are interested in using this algorithm in Python, you can use the scipy method [scipy.integrate.DOP853](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.DOP853.html). If you would like to create the algorithm yourself in Python, I would suggest looking at the sources in that scipy doc.

Hope this helps.
